### ISSUE TITLE
发现个有趣的现象0.0

### ISSUE THREAD

**Issue by Cat7373** [yeahwu/firefox-xx#14]
看了几个 APPID 的后台，似乎流量都没消耗多少，但是执行时间都在 95% 以上0.0

**Comment by Cat7373** [comment]
似乎大部分开销都来自 HEAD 请求而非 GET、POST 请求，怀疑是 XX-Net 测试 Appid 可用性。。。

**Comment by Cat7373** [comment]
突然想到。。。
直接接受公众捐献的 Appid，而非获取权限后重新部署有一定的风险。
在服务端插入点小代码，偷偷抓 UA 跟 Cookies，然后就可以轻松盗取别人的账号，至于 IP，用 相同 Appid 访问应该就是同一个。

**Comment by xxnet** [comment]
维护连接是使用了HEAD，不过如果没有连接会停下来。

大部分情况下资源是足够的，也没有人报问题，就没有再继续优化下去。
目前可以通过减少连接池数量和保持时间来减少这个开销。
终极的解决方案是HTTP/2，完全不用HEAD请求，不过工作量有点大

**Comment by Cat7373** [comment]
所以为什么@xxnet 会看到这个 - -
难道真的跟@yeahwu 是一个人- -

**Comment by xxnet** [comment]
在 2016年1月27日 下午9:02，Cat73 <notifications@github.com>写道：

> 突然想到。。。
> 直接接受公众捐献的 Appid，而非获取权限后重新部署有一定的风险。
> 在服务端插入点小代码，偷偷抓 UA 跟 Cookies，然后就可以轻松盗取别人的账号，至于 IP，用 相同 Appid 访问应该就是同一个。
>
> 是的，所以到目前为止，XX-Net的公共appid都是我自己部署的，贡献的方式也是转移控制权限才接受的。

**Comment by Cat7373** [comment]
@xxnet 好吧 似乎你点了Watch....

**Comment by xxnet** [comment]
2016-01-27 21:03 GMT+08:00 Cat73 <notifications@github.com>:

> 所以为什么@xxnet <https://github.com/xxnet> 会看到这个 - -
> 难道真的跟@yeahwu <https://github.com/yeahwu> 是一个人- -
>
> 这都被你发现了

**Comment by yeahwu** [comment]
哎呦，迟到了。因为面对的用户群是新手用户，着重考虑可用性，公共id安全性可能弱了点哈。
现在不是有新的选择了么，x-tunnel，有安全需求的可以鼓励他们过渡到x-tunnel,
ID消耗，我定期查看了一下，平均每天消耗三分之二左右，能抗到过年。

**Comment by xxnet** [comment]
​最近x_tunnel推出，收到不少appid，继续推广下去，公共appid就不愁了

**Comment by yeahwu** [comment]
目前发现大家还是比较欢迎x-tunnel的，简单，高效，故障率低。再成熟点，解决代理问题，可以成为杀手极工具。

**Comment by Cat7373** [comment]
連出的頻寬	
已使用 0.08 GB，共 1 GB

連入頻寬	
已使用 0.10 GB，共 1 GB

前端執行個體時數	
已執行 28.06 個執行個體小時，共 28 個執行個體小時

看着这么多流量因为执行时间满了而无法使用，心疼啊。。。

**Comment by Cat7373** [comment]
咦，居然没有重开的按钮，越来越不懂 Github 了0.0
